services:
  api:
    build: .
    container_name: api_proteccion
    restart: always
    env_file:
      - .env
    ports:
      - "3002:3002"
    volumes:
      - /api/uploads:/app/uploads
      - /api/files:/app/files
    extra_hosts:
      - "host.docker.internal:host-gateway"
